/**
 * This file is auto-generated by openapi-typescript.
 * DO NOT MODIFY IT MANUALLY.
 * 
 * To regenerate, run: npm run generate-types
 */

export interface paths {
  "/api/submit": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            date: string
            first_name: string
            last_name: string
          }
        }
      }
      responses: {
        200: {
          content: {
            "application/json": {
              success: boolean
            }
          }
        }
        400: {
          content: {
            "application/json": {
              success: false
              error: {
                [key: string]: string[]
              }
            }
          }
        }
      }
    }
  }
  "/api/history": {
    get: {
      parameters: {
        query: {
          date: string
          first_name?: string
          last_name?: string
        }
      }
      responses: {
        200: {
          content: {
            "application/json": {
              items: Array<{
                date: string
                first_name: string
                last_name: string
                count: number
              }>
              total: number
            }
          }
        }
      }
    }
  }
  "/api/unique-names": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              first_names: string[]
              last_names: string[]
            }
          }
        }
      }
    }
  }
}

export type components = {
  schemas: {
    SubmitFormRequest: {
      date: string
      first_name: string
      last_name: string
    }
    SubmitFormResponse: {
      success: boolean
    }
    SubmitFormErrorResponse: {
      success: false
      error: {
        [key: string]: string[]
      }
    }
    HistoryItem: {
      date: string
      first_name: string
      last_name: string
      count: number
    }
    HistoryResponse: {
      items: components["schemas"]["HistoryItem"][]
      total: number
    }
    UniqueNamesResponse: {
      first_names: string[]
      last_names: string[]
    }
  }
}

export type operations = {
  submitForm: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitFormRequest"]
      }
    }
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SubmitFormResponse"]
        }
      }
      400: {
        content: {
          "application/json": components["schemas"]["SubmitFormErrorResponse"]
        }
      }
    }
  }
  getHistory: {
    parameters: {
      query: {
        date: string
        first_name?: string
        last_name?: string
      }
    }
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HistoryResponse"]
        }
      }
    }
  }
  getUniqueNames: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UniqueNamesResponse"]
        }
      }
    }
  }
}

